apps/transport/lib/transport_web/api/router.ex
defmodule TransportWeb.API.Router do
  use TransportWeb, :router
  use Sentry.PlugCapture

  pipeline :accept_json do
    plug(:accepts, ["json"])
  end

  pipeline :api do
    plug(CORSPlug, origin: "*")
    plug(OpenApiSpex.Plug.PutApiSpec, module: TransportWeb.API.Spec)
    plug(Sentry.PlugContext)
  end

  scope "/api/" do
    pipe_through([:accept_json, :api])

    scope "/aoms" do
      get("/", TransportWeb.API.AomController, :by_coordinates)
      get("/geojson", TransportWeb.API.AomController, :geojson)
      get("/:insee", TransportWeb.API.AomController, :by_insee)
    end

    scope "/stats" do
      get("/", TransportWeb.API.StatsController, :index)
      get("/regions", TransportWeb.API.StatsController, :regions)
      get("/bike-sharing", TransportWeb.API.StatsController, :bike_sharing)
      get("/quality", TransportWeb.API.StatsController, :quality)
    end

    get("/openapi", OpenApiSpex.Plug.RenderSpec, :show)

    get("/places", TransportWeb.API.PlacesController, :autocomplete)

    scope "/datasets" do
      get("/", TransportWeb.API.DatasetController, :datasets)
      get("/:id", TransportWeb.API.DatasetController, :by_id)
      get("/:id/geojson", TransportWeb.API.DatasetController, :geojson_by_id)
    end
  end

  @spec swagger_info :: %{info: %{title: binary(), version: binary()}}
  def swagger_info,
    do: %{
      info: %{
        version: "1.0",
        title: "Transport.data.gouv.fr API"
      }
    }
end

apps/transport/lib/transport_web/plugs/router.ex
defmodule TransportWeb.Plugs.Router do
  use Plug.Router

  plug(:match)
  plug(:dispatch)

  # Technically, we should probably route to the Unlock.Endpoint
  # but because the current file is very deep in the pipeline at
  # the moment, this would mean double logging etc. The Unlock.Endpoint
  # is as a consequence not used, except for testing!
  match(_, host: "proxy.", to: Unlock.Router)
  match("/api/*_", to: TransportWeb.API.Router)
  match("/gbfs/*_", to: GBFS.Router)
  match(_, to: TransportWeb.Router)
end

apps/transport/lib/transport_web/router.ex
defmodule TransportWeb.Router do
  use TransportWeb, :router
  use Sentry.PlugCapture

  defimpl Plug.Exception, for: Phoenix.Template.UndefinedError do
    def status(_exception), do: 404
    def actions(e), do: [%{label: "Not found", handler: {IO, :puts, ["Template not found: #{inspect(e)}"]}}]
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_locale)
    plug(:assign_current_user)
    plug(:assign_contact_email)
    plug(:assign_token)
    plug(:assign_mix_env)
    plug(Sentry.PlugContext)
  end

  pipeline :accept_json do
    plug(:accepts, ["json"])
  end

  pipeline :authenticated do
    plug(:browser)
    plug(:authentication_required)
  end

  pipeline :admin_rights do
    plug(:authenticated)
    plug(:transport_data_gouv_member)
  end

  get("/swaggerui", OpenApiSpex.Plug.SwaggerUI, path: "/api/openapi")

  scope "/", TransportWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/real_time", PageController, :real_time)
    get("/partners", PageController, :partners)
    get("/conditions", PageController, :conditions)
    get("/infos_producteurs", PageController, :infos_producteurs)

    scope "/espace_producteur" do
      pipe_through([:authenticated])
      get("/", PageController, :espace_producteur)
    end

    get("/stats", StatsController, :index)
    get("/atom.xml", AtomController, :index)
    post("/send_mail", ContactController, :send_mail)
    get("/aoms", AOMSController, :index)
    get("/aoms.csv", AOMSController, :csv)

    scope "/datasets" do
      get("/", DatasetController, :index)
      get("/:slug/", DatasetController, :details)
      get("/aom/:aom", DatasetController, :by_aom)
      get("/region/:region", DatasetController, :by_region)
      get("/commune/:insee_commune", DatasetController, :by_commune_insee)

      scope "/:dataset_id" do
        pipe_through([:authenticated])
        post("/followers", FollowerController, :toggle)
        post("/discussions", DiscussionController, :post_discussion)
        post("/discussions/:id_", DiscussionController, :post_answer)
      end
    end

    scope "/resources" do
      get("/:id", ResourceController, :details)

      scope "/update" do
        pipe_through([:authenticated])
        get("/_choose_action", ResourceController, :choose_action)
        get("/datasets", ResourceController, :datasets_list)

        scope "/datasets/:dataset_id/resources" do
          get("/", ResourceController, :resources_list)
          post("/", ResourceController, :post_file)
          get("/_new_resource/", ResourceController, :form)
          get("/:resource_id/", ResourceController, :form)
          post("/:resource_id/", ResourceController, :post_file)
        end
      end
    end

    scope "/backoffice", Backoffice, as: :backoffice do
      pipe_through([:admin_rights])
      get("/", PageController, :index)

      get("/dashboard", DashboardController, :index)
      # NOTE: by default no layout are automatically picked at time of writing
      # for live views, so an explicit call is needed
      # See https://hexdocs.pm/phoenix_live_view/live-layouts.html
      live("/proxy-config", ProxyConfigLive,
        layout: {TransportWeb.LayoutView, :app},
        session: {TransportWeb.Backoffice.ProxyConfigLive, :build_session, []}
      )

      scope "/datasets" do
        get("/new", PageController, :new)
        get("/:id/edit", PageController, :edit)
        post("/", DatasetController, :post)
        post("/:id/_import", DatasetController, :import_from_data_gouv_fr)
        post("/:id/_delete", DatasetController, :delete)
        post("/_all_/_import_validate", DatasetController, :import_validate_all)
        post("/_all_/_validate", DatasetController, :validate_all)
        post("/_all_/_force_validate", DatasetController, :force_validate_all)
        post("/:id/_import_validate", DatasetController, :import_validate_all)
        post("/:id/_validate", DatasetController, :validation)
        post("/:id/_launch_resource_conversion", DatasetController, :launch_resources_conversions)
      end

      scope "/partners" do
        get("/", PartnerController, :partners)
        post("/", PartnerController, :post_partner)
      end
    end

    # Authentication

    scope "/login" do
      get("/", SessionController, :new)
      get("/explanation", PageController, :login)
      get("/callback", SessionController, :create)
    end

    get("/logout", SessionController, :delete)

    scope "/validation" do
      get("/", ValidationController, :index)
      post("/", ValidationController, :validate)
      get("/:id", ValidationController, :show)
    end

    # old static pages that have been moved to doc.transport
    get("/faq", Redirect, external: "https://doc.transport.data.gouv.fr/foire-aux-questions")

    get("/guide", Redirect,
      external:
        "https://doc.transport.data.gouv.fr/producteurs/operateurs-de-transport-regulier-de-personnes/publier-des-horaires-theoriques-de-transport-regulier"
    )

    get("/legal", Redirect,
      external: "https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/cadre-juridique-harmonise"
    )

    # old static pages that have been moved to blog.transport
    get("/blog/2019_04_26_interview_my_bus", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/entretien-avec-fr%C3%A9d%C3%A9ric-pacotte-co-fondateur-et-ceo-de-mybus/"
    )

    get("/blog/2019_10_24_itw-gueret", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/cr%C3%A9ation-dun-fichier-gtfs-interview-avec-le-grand-gu%C3%A9ret/"
    )

    get("/blog/2020_01_16_donnees_perimees.md", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/donn%C3%A9es-p%C3%A9rim%C3%A9es-donn%C3%A9es-inutilis%C3%A9es/"
    )
  end

  # private

  defp put_locale(conn, _) do
    case conn.params["locale"] || get_session(conn, :locale) do
      nil ->
        Gettext.put_locale("fr")
        conn |> put_session(:locale, "fr")

      locale ->
        Gettext.put_locale(locale)
        conn |> put_session(:locale, locale)
    end
  end

  defp assign_mix_env(conn, _) do
    assign(conn, :mix_env, Mix.env())
  end

  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end

  defp assign_contact_email(conn, _) do
    assign(conn, :contact_email, Application.get_env(:transport, :contact_email))
  end

  defp assign_token(conn, _) do
    assign(conn, :token, get_session(conn, :token))
  end

  defp authentication_required(conn, _) do
    case conn.assigns[:current_user] do
      nil ->
        conn
        |> put_flash(:info, dgettext("alert", "You need to be connected before doing this."))
        |> redirect(to: Helpers.page_path(conn, :login, redirect_path: current_path(conn)))
        |> halt()

      _ ->
        conn
    end
  end

  # NOTE: method visibility set to public because we need to call the same logic from LiveView
  def is_transport_data_gouv_member?(current_user) do
    current_user
    |> Map.get("organizations", [])
    |> Enum.any?(fn org -> org["slug"] == "equipe-transport-data-gouv-fr" end)
  end

  defp transport_data_gouv_member(conn, _) do
    if is_transport_data_gouv_member?(conn.assigns[:current_user]) do
      conn
    else
      conn
      |> put_flash(:error, dgettext("alert", "You need to be a member of the transport.data.gouv.fr team."))
      |> redirect(to: Helpers.page_path(conn, :login, redirect_path: current_path(conn)))
      |> halt()
    end
  end
end

apps/transport/lib/transport_web/views/layout_view.ex
defmodule TransportWeb.LayoutView do
  use TransportWeb, :view
  alias __MODULE__
  alias Phoenix.Controller

  def current_path(conn) do
    Controller.current_path(conn)
  end

  def has_flash(conn) do
    # it's not nice to depend on some internal state, but it does not seems to have a better way
    # to check if the `put_flash` function has been called, and it's important for error pages
    not is_nil(conn.private[:phoenix_flash])
  end

  def add_locale_to_url(conn, locale) do
    params = conn.params |> Map.put("locale", locale)
    "#{conn.request_path}?#{Plug.Conn.Query.encode(params)}"
  end
end

apps/transport/lib/transport_web/templates/layout/_footer.html.eex
<footer class="footer" role="contentinfo" id="footer">
  <a href="#mail_form" class="mail__button" aria-label="<%= dgettext("page-index", "Ask for help") %>">
    <i class="fas icon--envelope"></i>
    <span><%= dgettext("page-index", "Ask for help") %></span>
  </a>
  <div class="modal__backdrop" id="mail_form">
    <div class="footer__contact">
      <a class="footer__contact--close" href="#" aria-label="<%= dgettext("page-index", "Close the form") %>">
        <i class="fas icon--times-circle"></i>
      </a>
      <%= form_for @conn, contact_path(@conn, :send_mail), fn f -> %>
      <h3>Contact</h3>
      <%= email_input(f, :email, placeholder: gettext("Email address")) %>
      <%= text_input(f, :name, placeholder: "your name", class: "form-special-field", tabindex: "-1", autocomplete: "off") %>
      <%= text_input(f, :topic, value: gettext("Question about transport.data.gouv.fr")) %>
      <%= textarea(f, :demande, placeholder: gettext("Ask for help")) %>
      <%= submit gettext("Send email") %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="footer__logo">
    <%= link("Ministère de la transition écologique", to: "https://www.ecologique-solidaire.gouv.fr/", class: "ministere-link")%>
    <%= link(img_tag("/images/logo-footer.svg", alt: "transport.data.gouv.fr"), to: "/") %>
  </div>
  <ul class="footer__links">
    <%= if assigns[:contact_email] do %>
      <li>
        <a class="footer__link footer__link--contact" href='mailto:<%= @contact_email %>' role="link">
          <%= gettext "Contact" %>
        </a>
      </li>
    <% end %>
    <li>
      <a class="footer__link footer__link--tos" href="https://doc.transport.data.gouv.fr/reutilisateurs/apis/" role="link">API</a>
    </li>
    <li>
      <a class="footer__link footer__link--tos" href="https://doc.transport.data.gouv.fr/foire-aux-questions" role="link">FAQ</a>
    </li>
    <li>
      <a class="footer__link footer__link--tos" href="https://github.com/etalab/transport-site/" role="link"><%= gettext("Source code")%></a>
    </li>
    <li>
      <a class="footer__link footer__link--tos" href="/legal" role="link">
        <%= gettext "Legal Information" %>
      </a>
    </li>
  </ul>
</div>
</footer>

apps/transport/lib/transport_web/templates/layout/_header.html.eex
<header class="navbar">
  <div class="navbar__container">
    <a href="/" class="navbar__home">
      <%= img_tag("/images/logo-header.svg", alt: gettext("transport.data.gouv.fr"), class: "navbar__logo-mariane") %>
      <%= img_tag("/images/logo-black.svg", alt: gettext("transport.data.gouv.fr"), class: "navbar__logo-black") %>
    </a>
    <nav role="navigation">
      <a href="#menu">
        <div class="nav__hamburger">
          <div></div>
          <div></div>
          <div></div>
        </div>
      </a>
      <div id="menu">
        <a id="close-menu" href="#" aria-label="<%= dgettext("page-index", "Close the menu") %>">
          <i class="fas icon--times-circle"></i>&nbsp
        </a>
        <ul class="nav__links top-nav-links">
          <li class="nav__item">
            <%= link(gettext("Documentation"), to: "https://doc.transport.data.gouv.fr") %>
          </li>
          <li class="nav__item">
            <div class="dropdown">
              <%= gettext("Tools") %>
              <div class="dropdown-content">
                <%= link(gettext("Check a GTFS file's quality"), to: "/validation") %>
                <%= link(gettext("Service status"), to: "https://stats.uptimerobot.com/q7nqyiO9yQ", target: "_blank") %>
              </div>
            </div>
          </li>
          <li class="nav__item">
            <%= link(gettext("Producer infos"), to: page_path(@conn, :infos_producteurs)) %>
          </li>
          <li class="nav__item">
            <%= link(gettext("Blog"), to: "https://blog.transport.data.gouv.fr") %>
          </li>
          <%= if assigns[:current_user] do %>
            <li class="nav__item">
              <div class="dropdown">
                <div class="user-name-display">
                  <span class="nav__username">
                    <%= if assigns[:current_user]["first_name"] || assigns[:current_user]["last_name"] do %>
                        <%= assigns[:current_user]["first_name"] %> <%= assigns[:current_user]["last_name"] %>
                    <% else %>
                        <%= gettext("My account") %>
                    <% end %>
                  </span>
                  <%= if assigns[:current_user]["avatar_thumbnail"] do %>
                    <img src="<%= assigns[:current_user]["avatar_thumbnail"] %>" alt="" class="nav__avatar"> </img>
                  <% end %>
                </div>
              <div class="dropdown-content">
                <%= if admin?(assigns[:current_user]) do %>
                  <%= link("Administration", to: "/backoffice") %>
                <% end %>
                <a class="navigation__link nagivation__link--logout" href="<%= session_path @conn, :delete, redirect_path: current_path(@conn) %>" role="link">
                  <i class="icon icon--logout" aria-hidden="true"></i>
                  <span><%= gettext "Sign Out" %></span>
                </a>
              </div>
            </div>
          </li>
        <% else %>
          <li class="nav__item">
            <a class="navigation__link navigation__link--login" href="<%= page_path @conn, :login, redirect_path: current_path(@conn) %>" role="link">
              <i class="icon icon--login" aria-hidden="true"></i>
              <span><%= gettext "Sign In" %></span>
            </a>
          </li>
        <% end %>
          <li class="nav__item">
            <div class="dropdown">
              <%= if get_session(@conn, :locale) == "fr" do %>
                <img src="<%= static_path(@conn, "/images/icons/fr.png") %>" height=24 >
              <% else %>
                <img src="<%= static_path(@conn, "/images/icons/en.png") %>" height=24 >
              <% end %>
              <div class="dropdown-content">
                <%= link(to: add_locale_to_url(@conn, "fr")) do %>
                  Français
                <% end %>
                <%= link(to: add_locale_to_url(@conn, "en")) do %>
                  English
                <% end %>
              </div>
            </div>
          </li>
      </ul>
    </div>
  </nav>
</div>
</header>

apps/transport/lib/transport_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="DINSIC">
    <meta name="csrf" content="<%= get_csrf_token() %>">

    <% seo = metadata(assigns) %>
    <meta name="description" content='<%= seo[:description] || dgettext("seo", "Publish, improve and reuse French public transport data") %>'>
    <title><%= seo[:title] || dgettext("seo", "National Access Point for transport open data") %></title>

    <link rel="stylesheet" media="all" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="alternate" type="application/atom+xml" href="<%= atom_url(@conn, :index) %>" title="Resources feed" >
    <%= if assigns[:mix_env] == :prod do %>
    <!-- Polyfill for css grid-->
    <script type="text/javascript">
    if(/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
      document.write('<script src="https://unpkg.com/@babel/polyfill@7.0.0/dist/polyfill.js"><\/script>');
      document.write('<script src="https://unpkg.com/url-polyfill@1.0.14/url-polyfill.js"><\/script>');
    }
    </script>
    <!-- Piwik -->
    <script type="text/javascript">
      var _paq = _paq || [];
      _paq.push(["setDomains", ["*.transport.data.gouv.fr","*.transport.data.gouv.fr"]]);
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//stats.data.gouv.fr/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', '58']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <noscript><p><img src="//stats.data.gouv.fr/piwik.php?idsite=58" style="border:0;" alt="" /></p></noscript>
    <!-- End Piwik Code -->
    <% end %>
  </head>

  <body>
    <%= render(LayoutView, "_header.html", assigns) %>

    <main class="layout-main" role="main">
      <%= if has_flash(@conn) do %>
        <%= if get_flash(@conn, :info) do %>
          <p class="notification"><%= get_flash(@conn, :info) %></p>
        <% end %>
        <%= if get_flash(@conn, :errors) do %>
          <%= for error <- get_flash(@conn, :errors) do %>
            <p class="message message--error"><%= error %></p>
          <% end %>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
            <p class="message message--error"><%= get_flash(@conn, :error) %></p>
        <% end %>
      <% end %>

      <%= @inner_content %>
    </main>

    <%= render(LayoutView, "_footer.html", assigns) %>
  </body>
</html>