apps/transport/lib/transport_web/api/router.ex
defmodule TransportWeb.API.Router do
  use TransportWeb, :router
  use Sentry.PlugCapture

  pipeline :accept_json do
    plug(:accepts, ["json"])
  end

  pipeline :api do
    plug(CORSPlug, origin: "*")
    plug(OpenApiSpex.Plug.PutApiSpec, module: TransportWeb.API.Spec)
    plug(Sentry.PlugContext)
  end

  scope "/api/" do
    pipe_through([:accept_json, :api])

    scope "/aoms" do
      get("/", TransportWeb.API.AomController, :by_coordinates)
      get("/geojson", TransportWeb.API.AomController, :geojson)
      get("/:insee", TransportWeb.API.AomController, :by_insee)
    end

    scope "/stats" do
      get("/", TransportWeb.API.StatsController, :index)
      get("/regions", TransportWeb.API.StatsController, :regions)
      get("/bike-sharing", TransportWeb.API.StatsController, :bike_sharing)
      get("/quality", TransportWeb.API.StatsController, :quality)
    end

    get("/openapi", OpenApiSpex.Plug.RenderSpec, :show)

    get("/places", TransportWeb.API.PlacesController, :autocomplete)

    scope "/datasets" do
      get("/", TransportWeb.API.DatasetController, :datasets)
      get("/:id", TransportWeb.API.DatasetController, :by_id)
      get("/:id/geojson", TransportWeb.API.DatasetController, :geojson_by_id)
    end
  end

  @spec swagger_info :: %{info: %{title: binary(), version: binary()}}
  def swagger_info,
    do: %{
      info: %{
        version: "1.0",
        title: "Transport.data.gouv.fr API"
      }
    }
end

apps/transport/lib/transport_web/plugs/router.ex
defmodule TransportWeb.Plugs.Router do
  use Plug.Router

  plug(:match)
  plug(:dispatch)

  # Technically, we should probably route to the Unlock.Endpoint
  # but because the current file is very deep in the pipeline at
  # the moment, this would mean double logging etc. The Unlock.Endpoint
  # is as a consequence not used, except for testing!
  match(_, host: "proxy.", to: Unlock.Router)
  match("/api/*_", to: TransportWeb.API.Router)
  match("/gbfs/*_", to: GBFS.Router)
  match(_, to: TransportWeb.Router)
end

apps/transport/lib/transport_web/router.ex
defmodule TransportWeb.Router do
  use TransportWeb, :router
  use Sentry.PlugCapture

  defimpl Plug.Exception, for: Phoenix.Template.UndefinedError do
    def status(_exception), do: 404
    def actions(e), do: [%{label: "Not found", handler: {IO, :puts, ["Template not found: #{inspect(e)}"]}}]
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_locale)
    plug(:assign_current_user)
    plug(:assign_contact_email)
    plug(:assign_token)
    plug(:assign_mix_env)
    plug(Sentry.PlugContext)
  end

  pipeline :accept_json do
    plug(:accepts, ["json"])
  end

  pipeline :authenticated do
    plug(:browser)
    plug(:authentication_required)
  end

  pipeline :admin_rights do
    plug(:authenticated)
    plug(:transport_data_gouv_member)
  end

  get("/swaggerui", OpenApiSpex.Plug.SwaggerUI, path: "/api/openapi")

  scope "/", TransportWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/real_time", PageController, :real_time)
    get("/partners", PageController, :partners)
    get("/conditions", PageController, :conditions)
    get("/infos_producteurs", PageController, :infos_producteurs)

    scope "/espace_producteur" do
      pipe_through([:authenticated])
      get("/", PageController, :espace_producteur)
    end

    get("/stats", StatsController, :index)
    get("/atom.xml", AtomController, :index)
    post("/send_mail", ContactController, :send_mail)
    get("/aoms", AOMSController, :index)
    get("/aoms.csv", AOMSController, :csv)

    scope "/datasets" do
      get("/", DatasetController, :index)
      get("/:slug/", DatasetController, :details)
      get("/aom/:aom", DatasetController, :by_aom)
      get("/region/:region", DatasetController, :by_region)
      get("/commune/:insee_commune", DatasetController, :by_commune_insee)

      scope "/:dataset_id" do
        pipe_through([:authenticated])
        post("/followers", FollowerController, :toggle)
        post("/discussions", DiscussionController, :post_discussion)
        post("/discussions/:id_", DiscussionController, :post_answer)
      end
    end

    scope "/resources" do
      get("/:id", ResourceController, :details)

      scope "/update" do
        pipe_through([:authenticated])
        get("/_choose_action", ResourceController, :choose_action)
        get("/datasets", ResourceController, :datasets_list)

        scope "/datasets/:dataset_id/resources" do
          get("/", ResourceController, :resources_list)
          post("/", ResourceController, :post_file)
          get("/_new_resource/", ResourceController, :form)
          get("/:resource_id/", ResourceController, :form)
          post("/:resource_id/", ResourceController, :post_file)
        end
      end
    end

    scope "/backoffice", Backoffice, as: :backoffice do
      pipe_through([:admin_rights])
      get("/", PageController, :index)

      get("/dashboard", DashboardController, :index)
      # NOTE: by default no layout are automatically picked at time of writing
      # for live views, so an explicit call is needed
      # See https://hexdocs.pm/phoenix_live_view/live-layouts.html
      live("/proxy-config", ProxyConfigLive,
        layout: {TransportWeb.LayoutView, :app},
        session: {TransportWeb.Backoffice.ProxyConfigLive, :build_session, []}
      )

      scope "/datasets" do
        get("/new", PageController, :new)
        get("/:id/edit", PageController, :edit)
        post("/", DatasetController, :post)
        post("/:id/_import", DatasetController, :import_from_data_gouv_fr)
        post("/:id/_delete", DatasetController, :delete)
        post("/_all_/_import_validate", DatasetController, :import_validate_all)
        post("/_all_/_validate", DatasetController, :validate_all)
        post("/_all_/_force_validate", DatasetController, :force_validate_all)
        post("/:id/_import_validate", DatasetController, :import_validate_all)
        post("/:id/_validate", DatasetController, :validation)
        post("/:id/_launch_resource_conversion", DatasetController, :launch_resources_conversions)
      end

      scope "/partners" do
        get("/", PartnerController, :partners)
        post("/", PartnerController, :post_partner)
      end
    end

    # Authentication

    scope "/login" do
      get("/", SessionController, :new)
      get("/explanation", PageController, :login)
      get("/callback", SessionController, :create)
    end

    get("/logout", SessionController, :delete)

    scope "/validation" do
      get("/", ValidationController, :index)
      post("/", ValidationController, :validate)
      get("/:id", ValidationController, :show)
    end

    # old static pages that have been moved to doc.transport
    get("/faq", Redirect, external: "https://doc.transport.data.gouv.fr/foire-aux-questions")

    get("/guide", Redirect,
      external:
        "https://doc.transport.data.gouv.fr/producteurs/operateurs-de-transport-regulier-de-personnes/publier-des-horaires-theoriques-de-transport-regulier"
    )

    get("/legal", Redirect,
      external: "https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/cadre-juridique-harmonise"
    )

    # old static pages that have been moved to blog.transport
    get("/blog/2019_04_26_interview_my_bus", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/entretien-avec-fr%C3%A9d%C3%A9ric-pacotte-co-fondateur-et-ceo-de-mybus/"
    )

    get("/blog/2019_10_24_itw-gueret", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/cr%C3%A9ation-dun-fichier-gtfs-interview-avec-le-grand-gu%C3%A9ret/"
    )

    get("/blog/2020_01_16_donnees_perimees.md", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/donn%C3%A9es-p%C3%A9rim%C3%A9es-donn%C3%A9es-inutilis%C3%A9es/"
    )
  end

  # private

  defp put_locale(conn, _) do
    case conn.params["locale"] || get_session(conn, :locale) do
      nil ->
        Gettext.put_locale("fr")
        conn |> put_session(:locale, "fr")

      locale ->
        Gettext.put_locale(locale)
        conn |> put_session(:locale, locale)
    end
  end

  defp assign_mix_env(conn, _) do
    assign(conn, :mix_env, Mix.env())
  end

  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end

  defp assign_contact_email(conn, _) do
    assign(conn, :contact_email, Application.get_env(:transport, :contact_email))
  end

  defp assign_token(conn, _) do
    assign(conn, :token, get_session(conn, :token))
  end

  defp authentication_required(conn, _) do
    case conn.assigns[:current_user] do
      nil ->
        conn
        |> put_flash(:info, dgettext("alert", "You need to be connected before doing this."))
        |> redirect(to: Helpers.page_path(conn, :login, redirect_path: current_path(conn)))
        |> halt()

      _ ->
        conn
    end
  end

  # NOTE: method visibility set to public because we need to call the same logic from LiveView
  def is_transport_data_gouv_member?(current_user) do
    current_user
    |> Map.get("organizations", [])
    |> Enum.any?(fn org -> org["slug"] == "equipe-transport-data-gouv-fr" end)
  end

  defp transport_data_gouv_member(conn, _) do
    if is_transport_data_gouv_member?(conn.assigns[:current_user]) do
      conn
    else
      conn
      |> put_flash(:error, dgettext("alert", "You need to be a member of the transport.data.gouv.fr team."))
      |> redirect(to: Helpers.page_path(conn, :login, redirect_path: current_path(conn)))
      |> halt()
    end
  end
end

apps/transport/lib/transport_web/controllers/backoffice/dashboard_controller.ex
defmodule TransportWeb.Backoffice.DashboardController do
  use TransportWeb, :controller

  # alias DB.{Dataset, LogsImport, LogsValidation, Region, Repo, Resource}
  # import Ecto.Query
  require Logger

  @dashboard_import_count_sql File.read!("lib/queries/dashboard_import_count.sql")

  def index(conn, _params) do
    data =
      @dashboard_import_count_sql
      |> DB.Repo.query!()

    import_count_by_dataset_and_by_day =
      data.rows
      |> Enum.group_by(
        fn [dataset_id, _, _, _] -> dataset_id end,
        fn [_, date, import_count, success_count] -> {date, import_count, success_count} end
      )
      |> Enum.sort_by(fn {key, _value} -> key end)

    conn
    |> render("index.html", import_count_by_dataset_and_by_day: import_count_by_dataset_and_by_day)
  end
end

apps/transport/lib/transport_web/controllers/backoffice/dataset_controller.ex
defmodule TransportWeb.Backoffice.DatasetController do
  use TransportWeb, :controller
  alias Datagouvfr.Client.Datasets

  alias DB.{Dataset, ImportDataWorker, Repo}
  alias Transport.{GtfsConversions, ImportData, ImportDataWorker}
  require Logger

  @spec post(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def post(%Plug.Conn{} = conn, params) do
    msgs = %{
      success: %{
        "edit" => dgettext("backoffice_dataset", "Dataset edited with success"),
        "new" => dgettext("backoffice_dataset", "Dataset added with success")
      },
      error: %{
        "edit" => dgettext("backoffice_dataset", "Could not edit dataset"),
        "new" => dgettext("backoffice_dataset", "Could not add dataset")
      }
    }

    with datagouv_id when not is_nil(datagouv_id) <- Datasets.get_id_from_url(params["url"]),
         {:ok, dg_dataset} <- ImportData.import_from_data_gouv(datagouv_id, params["type"]),
         params <- Map.merge(params, dg_dataset),
         {:ok, changeset} <- Dataset.changeset(params),
         {:ok, dataset} <- insert_dataset(changeset) do
      dataset
      |> Dataset.validate()
      |> flash(conn, msgs.success[params["action"]], msgs.error[params["action"]])
    else
      {:error, error} ->
        conn
        |> put_flash(:error, msgs.error[params["action"]])
        |> put_flash(:error, error)

      error ->
        Logger.error(error)

        conn
        |> put_flash(:error, msgs.error[params["action"]])
        |> put_flash(:error, "Unable to get datagouv id")
    end
    |> redirect_to_index()
  end

  @spec insert_dataset(Ecto.Changeset.t()) :: {:ok, binary} | {:error, binary}
  defp insert_dataset(changeset) do
    Repo.insert_or_update(changeset)
  rescue
    exception in Ecto.ConstraintError ->
      Logger.error("Constraint violation while inserting dataset: #{inspect(exception)}")

      {:error, "Problem while inserting the dataset in the database,
       a constraint has not been respected : '#{exception.constraint}'"}
  end

  @spec import_from_data_gouv_fr(Plug.Conn.t(), map) :: Plug.Conn.t()
  def import_from_data_gouv_fr(%Plug.Conn{} = conn, %{"id" => id, "stay_on_page" => "true"}),
    do: redirect(import_from_data_gouv_fr_aux(conn, id), to: backoffice_page_path(conn, :edit, id))

  def import_from_data_gouv_fr(%Plug.Conn{} = conn, %{"id" => id}),
    do: redirect_to_index(import_from_data_gouv_fr_aux(conn, id))

  @spec import_from_data_gouv_fr_aux(Plug.Conn.t(), integer()) :: Plug.Conn.t()
  defp import_from_data_gouv_fr_aux(conn, id) do
    Dataset
    |> Repo.get(id)
    |> import_data
    |> flash(
      conn,
      dgettext("backoffice_dataset", "Dataset imported with success"),
      dgettext("backoffice_dataset", "Dataset not imported")
    )
  end

  @spec delete(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def delete(%Plug.Conn{} = conn, %{"id" => id}) do
    Dataset
    |> Repo.get(id)
    |> Repo.delete()
    |> flash(
      conn,
      dgettext("backoffice_dataset", "Dataset deleted"),
      dgettext("backoffice", "Could not delete dataset")
    )
    |> redirect_to_index()
  end

  @spec import_validate_all(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def import_validate_all(%Plug.Conn{} = conn, _args) do
    ImportDataWorker.import_validate_all()

    conn
    |> put_flash(
      :info,
      dgettext("backoffice_dataset", "Import and validation of all datasets have been launch")
    )
    |> redirect_to_index()
  end

  @spec validate_all(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def validate_all(%Plug.Conn{} = conn, _args) do
    ImportDataWorker.validate_all()

    conn
    |> put_flash(
      :info,
      dgettext("backoffice_dataset", "validation of all datasets has been launched")
    )
    |> redirect_to_index()
  end

  @spec force_validate_all(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def force_validate_all(%Plug.Conn{} = conn, _args) do
    ImportDataWorker.force_validate_all()

    conn
    |> put_flash(
      :info,
      dgettext("backoffice_dataset", "validation of all datasets has been launch")
    )
    |> redirect_to_index()
  end

  @spec launch_resources_conversions(Plug.Conn.t(), map) :: Plug.Conn.t()
  def launch_resources_conversions(%Plug.Conn{} = conn, %{"id" => dataset_id}) do
    # force the conversion of GTFS resources to GeoJSON and NeTEx format
    res = GtfsConversions.convert_resources_of_dataset(dataset_id)

    res
    |> flash(
      conn,
      dgettext("backoffice_dataset", "resources conversion launched"),
      dgettext("backoffice_dataset", "no resource can be converted")
    )
    |> redirect(to: backoffice_page_path(conn, :edit, dataset_id))
  end

  ## Private functions

  @spec flash(:ok | {:ok, any} | {:error, any}, Plug.Conn.t(), binary, binary) :: Plug.Conn.t()
  defp flash({:ok, _message}, conn, ok_message, err_message),
    do: flash(:ok, conn, ok_message, err_message)

  defp flash(:ok, conn, ok_message, _err_message), do: put_flash(conn, :info, ok_message)

  defp flash({:error, %{errors: errors}}, conn, _ok, err_message) do
    errors_messages = for {_, {m, _}} <- errors, do: m
    messages = (errors_messages ++ [err_message]) |> Enum.uniq()
    put_flash(conn, :error, Enum.join(messages, ", "))
  end

  defp flash({:error, message}, conn, _ok, err),
    do: put_flash(conn, :error, "#{err} (#{message})")

  @spec import_data(Dataset.t() | nil) :: any()
  defp import_data(%Dataset{} = dataset), do: ImportData.import_dataset_logged(dataset)
  defp import_data(nil), do: {:error, dgettext("backoffice", "Unable to find dataset")}

  defp redirect_to_index(conn),
    do: redirect(conn, to: backoffice_page_path(conn, :index, conn.params |> Map.take(["q"])))
end

apps/transport/lib/transport_web/views/backoffice/dashboard_view.ex
defmodule TransportWeb.Backoffice.DashboardView do
  use TransportWeb, :view

  @spec cell_class({boolean(), boolean()}) :: binary()
  def cell_class({_import_count = 0, _success_count}), do: "no_import"

  def cell_class({import_count, _success_count = 0}) when import_count > 0, do: "only_failures"

  def cell_class({import_count, success_count}) when import_count != success_count, do: "some_failures"

  def cell_class({import_count, success_count}) when import_count == success_count, do: "only_successes"
end

apps/transport/lib/transport_web/views/backoffice/partner_view.ex
defmodule TransportWeb.Backoffice.PartnerView do
  use TransportWeb, :view
end

apps/transport/lib/transport_web/templates/backoffice/page/_dataset.html.eex
<tr>
  <td>
    <strong>
      <%= @dataset.spatial %>
    </strong>
  </td>
  <td class="is-centered">
    <a href="<%= dataset_path(@conn, :details, @dataset.slug) %>">
      <i class="fa fa-link"></i>
    </a>
  </td>
  <td class="is-centered">
    <a href="<%= Dataset.datagouv_url(@dataset) %>">
      <i class="fa fa-link"></i>
    </a>
  </td>
  <td><%= if @dataset.region do @dataset.region.nom else "" end %></td>
  <td><%= if @dataset.aom do @dataset.aom.insee_commune_principale else "" end %></td>
  <td>
    <%= end_date(@dataset) %>
  </td>
  <td class="bo_dataset_button">
    <%= form_for @conn, backoffice_dataset_path(@conn, :import_from_data_gouv_fr, @dataset.id, @conn.params), [nodiv: true], fn _ -> %>
      <%= submit "Importer", [class: "button", nodiv: true] %>
    <% end %>
  </td>
  <td class="bo_dataset_button">
    <%= live_render(@conn, TransportWeb.Live.ValidateDatasetView, session: %{"dataset_id" => @dataset.id, "locale" => get_session(@conn, :locale)}) %>
  </td>
  <td class="bo_dataset_button">
    <%= form_for @conn, backoffice_page_path(@conn, :edit, @dataset.id), [nodiv: true, method: "get"], fn _ -> %>
    <%= submit "Editer", [class: "button", nodiv: true] %>
  <% end %>
  </td>
  <td class="bo_dataset_button">
    <%= form_for @conn, backoffice_dataset_path(@conn, :delete, @dataset.id, @conn.params), [nodiv: true], fn _ -> %>
    <%= submit "Supprimer", [class: "button", nodiv: true] %>
  <% end %>
  </td>
</tr>

apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
<div class="pt-48 pb-48">
  <%= form_for @conn, backoffice_dataset_path(@conn, :post), fn f -> %>
  <h1>
    <%= if is_nil(@dataset) do %>
      <%= dgettext("backoffice", "Add a dataset") %>
    <% else %>
      <%= dgettext("backoffice", "Edit a dataset") %>
    <% end %>
  </h1>
  <%= text_input f, :url, [
        placeholder: dgettext("backoffice", "Dataset's url"),
        value: if not is_nil(@dataset) do Dataset.datagouv_url(@dataset) else "" end
      ] %>
  <%= text_input f, :spatial, [
        placeholder: dgettext("backoffice", "name"),
        value: if not is_nil(@dataset) do @dataset.spatial else "" end
      ] %>
  <%= select f, :type, @dataset_types, [
        selected: if not is_nil(@dataset) do @dataset.type else "public-transit" end ]%>
  <div class="panel mt-48">
    <div class="panel__header">
      <h4>
        <%= dgettext("backoffice", "Associated territory") %>
      </h4>
      <%= dgettext("backoffice", "Choose one") %>
    </div>
    <div class="panel__content">
      <%= checkbox f, :national_dataset, value: not is_nil(@dataset) && @dataset.region_id == 14 %><%= dgettext("backoffice", "National dataset") %>
    </div>
    <p class="separator">
      - <%= dgettext("resource", "or") %> -
    </p>
    <div class="panel__content">
      <%= dgettext("backoffice", "Dataset linked to a region") %>
      <%= select f, :region_id, Enum.map(@regions, &{&1.nom, &1.id}), [
        selected: if not is_nil(@dataset) do @dataset.region_id else "" end,
        prompt: "Pas un jeu de données régional"
        ]
      %>
    </div>
    <p class="separator">
      - <%= dgettext("resource", "or") %> -
    </p>
    <%= dgettext("backoffice", "Dataset linked to an AOM") %>
    <div class="panel__content">
    <%= if is_nil(@dataset) || is_nil(@dataset.aom) || is_nil(@dataset.aom.insee_commune_principale) do %>
      <%= live_render(@conn, TransportWeb.Live.CommuneField, session: %{"insee" => ""}) %>
    <% else %>
      <%= live_render(@conn, TransportWeb.Live.CommuneField, session: %{"insee" => @dataset.aom.insee_commune_principale}) %>
    <% end %>
    </div>
    <p class="separator">
      - <%= dgettext("resource", "or") %> -
    </p>
    <div class="panel__content">
      <%= dgettext("backoffice", "Dataset linked to a list of cities in data.gouv.fr") %>
      <div>
      <div class="pt-12">
        <%= text_input f, :associated_territory_name, [
        placeholder: dgettext("backoffice", "Name of the associtated territory (used in the title of the dataset)"),
        value: if not is_nil(@dataset) do @dataset.associated_territory_name else "" end
      ] %>
      </div>
      </div>
    </div>
  </div>
  <div class="backoffice_dataset_submit_buttons">
    <div>
    <%= if is_nil(@dataset) do %>
      <%= hidden_input f, :action, [value: "new"] %>
      <%= submit dgettext("backoffice", "Add") %>
    <% else %>
      <%= hidden_input f, :action, [value: "edit"] %>
      <%= submit dgettext("backoffice", "Edit") %>
    <% end %>
    <% end %>
    </div>
    <div>
      <%= link(dgettext("backoffice", "Cancel"), to: backoffice_page_path(@conn, :index)) %>
    </div>
  </div>
    <%= unless is_nil(@dataset) do %>
      <div class="is-centered mt-48">
        <%= dgettext("backoffice", "Other actions on the dataset") %>
      </div>
      <div class="backoffice_dataset_actions_buttons">
        <div>
          <%= form_for @conn, backoffice_dataset_path(@conn, :import_from_data_gouv_fr, @dataset.id, Map.put(@conn.params, "stay_on_page", true)), [nodiv: true], fn _ -> %>
            <%= submit "Importer", [class: "button", nodiv: true] %>
          <% end %>
        </div>

        <div>
          <%= live_render(@conn, TransportWeb.Live.ValidateDatasetView, session: %{"dataset_id" => @dataset.id, "locale" => get_session(@conn, :locale)}) %>
        </div>

        <div>
          <%= form_for @conn, backoffice_dataset_path(@conn, :delete, @dataset.id, @conn.params), [nodiv: true], fn _ -> %>
            <%= submit "Supprimer", [class: "button", nodiv: true] %>
          <% end %>
        </div>
      </div>
      <div class="backoffice_dataset_actions_buttons">
        <%= form_for @conn, backoffice_dataset_path(@conn, :launch_resources_conversions, @dataset.id), [nodiv: true], fn _ -> %>
          <%= submit dgettext("backoffice", "Generate community resources (GeoJSON and NeTEx)"), [class: "button"] %>
        <% end %>
      </div>
      <div class="dataset_import_validations_logs" id="imports_history">
        <h3><%= dgettext("backoffice", "Imports history") %></h3>
        <table>
          <tr>
            <th><%= dgettext("backoffice", "date / time") %></th>
            <th><%= dgettext("backoffice", "success") %></th>
            <th><%= dgettext("backoffice", "error message") %></th>
          </tr>
          <%= for row <- @import_logs do %>
            <tr>
              <td><%= row.timestamp %></td>
              <td><%= if row.is_success, do: "✔", else: "" %></td>
              <td><%= row.error_msg %></td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="dataset_import_validations_logs">
        <h3><%= dgettext("backoffice", "Validations history") %></h3>
        <%= for {resource, validations} <- @validation_logs do %>
          <%= if resource.format == "GTFS" do %>
            <h2><a href=<%= resource_path(@conn, :details, resource.id) %>><%= resource.title %></a> (#<%= resource.id %>)</h2>
          <% else %>
            <h2><%= resource.title %> (#<%= resource.id %>)</h2>
          <% end %>
          <table>
            <tr>
              <th><%= dgettext("backoffice", "date / time") %></th>
              <th><%= dgettext("backoffice", "success") %></th>
              <th><%= dgettext("backoffice", "error message") %></th>
              <th><%= dgettext("backoffice", "validation needed") %></th>
              <th><%= dgettext("backoffice", "explanation") %></th>
            </tr>
            <%= for row <- validations do %>
              <tr>
                <td><%= row.timestamp %></td>
                <td><%= if row.is_success, do: "✔", else: "" %></td>
                <td><%= row.error_msg %></td>
                <td><%=  if !row.skipped, do: "✔", else: "" %></td>
                <td><%= row.skipped_reason %></td>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
    <% end %>
</div>
<script src="/js/app.js"></script>