apps/transport/lib/transport_web/api/router.ex
defmodule TransportWeb.API.Router do
  use TransportWeb, :router
  use Sentry.PlugCapture

  pipeline :accept_json do
    plug(:accepts, ["json"])
  end

  pipeline :api do
    plug(CORSPlug, origin: "*")
    plug(OpenApiSpex.Plug.PutApiSpec, module: TransportWeb.API.Spec)
    plug(Sentry.PlugContext)
  end

  scope "/api/" do
    pipe_through([:accept_json, :api])

    scope "/aoms" do
      get("/", TransportWeb.API.AomController, :by_coordinates)
      get("/geojson", TransportWeb.API.AomController, :geojson)
      get("/:insee", TransportWeb.API.AomController, :by_insee)
    end

    scope "/stats" do
      get("/", TransportWeb.API.StatsController, :index)
      get("/regions", TransportWeb.API.StatsController, :regions)
      get("/bike-sharing", TransportWeb.API.StatsController, :bike_sharing)
      get("/quality", TransportWeb.API.StatsController, :quality)
    end

    get("/openapi", OpenApiSpex.Plug.RenderSpec, :show)

    get("/places", TransportWeb.API.PlacesController, :autocomplete)

    scope "/datasets" do
      get("/", TransportWeb.API.DatasetController, :datasets)
      get("/:id", TransportWeb.API.DatasetController, :by_id)
      get("/:id/geojson", TransportWeb.API.DatasetController, :geojson_by_id)
    end
  end

  @spec swagger_info :: %{info: %{title: binary(), version: binary()}}
  def swagger_info,
    do: %{
      info: %{
        version: "1.0",
        title: "Transport.data.gouv.fr API"
      }
    }
end

apps/transport/lib/transport_web/plugs/router.ex
defmodule TransportWeb.Plugs.Router do
  use Plug.Router

  plug(:match)
  plug(:dispatch)

  # Technically, we should probably route to the Unlock.Endpoint
  # but because the current file is very deep in the pipeline at
  # the moment, this would mean double logging etc. The Unlock.Endpoint
  # is as a consequence not used, except for testing!
  match(_, host: "proxy.", to: Unlock.Router)
  match("/api/*_", to: TransportWeb.API.Router)
  match("/gbfs/*_", to: GBFS.Router)
  match(_, to: TransportWeb.Router)
end

apps/transport/lib/transport_web/router.ex
defmodule TransportWeb.Router do
  use TransportWeb, :router
  use Sentry.PlugCapture

  defimpl Plug.Exception, for: Phoenix.Template.UndefinedError do
    def status(_exception), do: 404
    def actions(e), do: [%{label: "Not found", handler: {IO, :puts, ["Template not found: #{inspect(e)}"]}}]
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_locale)
    plug(:assign_current_user)
    plug(:assign_contact_email)
    plug(:assign_token)
    plug(:assign_mix_env)
    plug(Sentry.PlugContext)
  end

  pipeline :accept_json do
    plug(:accepts, ["json"])
  end

  pipeline :authenticated do
    plug(:browser)
    plug(:authentication_required)
  end

  pipeline :admin_rights do
    plug(:authenticated)
    plug(:transport_data_gouv_member)
  end

  get("/swaggerui", OpenApiSpex.Plug.SwaggerUI, path: "/api/openapi")

  scope "/", TransportWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/real_time", PageController, :real_time)
    get("/partners", PageController, :partners)
    get("/conditions", PageController, :conditions)
    get("/infos_producteurs", PageController, :infos_producteurs)

    scope "/espace_producteur" do
      pipe_through([:authenticated])
      get("/", PageController, :espace_producteur)
    end

    get("/stats", StatsController, :index)
    get("/atom.xml", AtomController, :index)
    post("/send_mail", ContactController, :send_mail)
    get("/aoms", AOMSController, :index)
    get("/aoms.csv", AOMSController, :csv)

    scope "/datasets" do
      get("/", DatasetController, :index)
      get("/:slug/", DatasetController, :details)
      get("/aom/:aom", DatasetController, :by_aom)
      get("/region/:region", DatasetController, :by_region)
      get("/commune/:insee_commune", DatasetController, :by_commune_insee)

      scope "/:dataset_id" do
        pipe_through([:authenticated])
        post("/followers", FollowerController, :toggle)
        post("/discussions", DiscussionController, :post_discussion)
        post("/discussions/:id_", DiscussionController, :post_answer)
      end
    end

    scope "/resources" do
      get("/:id", ResourceController, :details)

      scope "/update" do
        pipe_through([:authenticated])
        get("/_choose_action", ResourceController, :choose_action)
        get("/datasets", ResourceController, :datasets_list)

        scope "/datasets/:dataset_id/resources" do
          get("/", ResourceController, :resources_list)
          post("/", ResourceController, :post_file)
          get("/_new_resource/", ResourceController, :form)
          get("/:resource_id/", ResourceController, :form)
          post("/:resource_id/", ResourceController, :post_file)
        end
      end
    end

    scope "/backoffice", Backoffice, as: :backoffice do
      pipe_through([:admin_rights])
      get("/", PageController, :index)

      get("/dashboard", DashboardController, :index)
      # NOTE: by default no layout are automatically picked at time of writing
      # for live views, so an explicit call is needed
      # See https://hexdocs.pm/phoenix_live_view/live-layouts.html
      live("/proxy-config", ProxyConfigLive,
        layout: {TransportWeb.LayoutView, :app},
        session: {TransportWeb.Backoffice.ProxyConfigLive, :build_session, []}
      )

      scope "/datasets" do
        get("/new", PageController, :new)
        get("/:id/edit", PageController, :edit)
        post("/", DatasetController, :post)
        post("/:id/_import", DatasetController, :import_from_data_gouv_fr)
        post("/:id/_delete", DatasetController, :delete)
        post("/_all_/_import_validate", DatasetController, :import_validate_all)
        post("/_all_/_validate", DatasetController, :validate_all)
        post("/_all_/_force_validate", DatasetController, :force_validate_all)
        post("/:id/_import_validate", DatasetController, :import_validate_all)
        post("/:id/_validate", DatasetController, :validation)
        post("/:id/_launch_resource_conversion", DatasetController, :launch_resources_conversions)
      end

      scope "/partners" do
        get("/", PartnerController, :partners)
        post("/", PartnerController, :post_partner)
      end
    end

    # Authentication

    scope "/login" do
      get("/", SessionController, :new)
      get("/explanation", PageController, :login)
      get("/callback", SessionController, :create)
    end

    get("/logout", SessionController, :delete)

    scope "/validation" do
      get("/", ValidationController, :index)
      post("/", ValidationController, :validate)
      get("/:id", ValidationController, :show)
    end

    # old static pages that have been moved to doc.transport
    get("/faq", Redirect, external: "https://doc.transport.data.gouv.fr/foire-aux-questions")

    get("/guide", Redirect,
      external:
        "https://doc.transport.data.gouv.fr/producteurs/operateurs-de-transport-regulier-de-personnes/publier-des-horaires-theoriques-de-transport-regulier"
    )

    get("/legal", Redirect,
      external: "https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/cadre-juridique-harmonise"
    )

    # old static pages that have been moved to blog.transport
    get("/blog/2019_04_26_interview_my_bus", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/entretien-avec-fr%C3%A9d%C3%A9ric-pacotte-co-fondateur-et-ceo-de-mybus/"
    )

    get("/blog/2019_10_24_itw-gueret", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/cr%C3%A9ation-dun-fichier-gtfs-interview-avec-le-grand-gu%C3%A9ret/"
    )

    get("/blog/2020_01_16_donnees_perimees.md", Redirect,
      external:
        "https://blog.transport.data.gouv.fr/billets/donn%C3%A9es-p%C3%A9rim%C3%A9es-donn%C3%A9es-inutilis%C3%A9es/"
    )
  end

  # private

  defp put_locale(conn, _) do
    case conn.params["locale"] || get_session(conn, :locale) do
      nil ->
        Gettext.put_locale("fr")
        conn |> put_session(:locale, "fr")

      locale ->
        Gettext.put_locale(locale)
        conn |> put_session(:locale, locale)
    end
  end

  defp assign_mix_env(conn, _) do
    assign(conn, :mix_env, Mix.env())
  end

  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end

  defp assign_contact_email(conn, _) do
    assign(conn, :contact_email, Application.get_env(:transport, :contact_email))
  end

  defp assign_token(conn, _) do
    assign(conn, :token, get_session(conn, :token))
  end

  defp authentication_required(conn, _) do
    case conn.assigns[:current_user] do
      nil ->
        conn
        |> put_flash(:info, dgettext("alert", "You need to be connected before doing this."))
        |> redirect(to: Helpers.page_path(conn, :login, redirect_path: current_path(conn)))
        |> halt()

      _ ->
        conn
    end
  end

  # NOTE: method visibility set to public because we need to call the same logic from LiveView
  def is_transport_data_gouv_member?(current_user) do
    current_user
    |> Map.get("organizations", [])
    |> Enum.any?(fn org -> org["slug"] == "equipe-transport-data-gouv-fr" end)
  end

  defp transport_data_gouv_member(conn, _) do
    if is_transport_data_gouv_member?(conn.assigns[:current_user]) do
      conn
    else
      conn
      |> put_flash(:error, dgettext("alert", "You need to be a member of the transport.data.gouv.fr team."))
      |> redirect(to: Helpers.page_path(conn, :login, redirect_path: current_path(conn)))
      |> halt()
    end
  end
end

apps/transport/lib/transport_web/templates/page/_breadcrumbs.html.eex
<h4 class="is-grey">
  <%= dgettext("espace-producteurs", "Your producer space") %>
</h4>

apps/transport/lib/transport_web/templates/page/conditions.html.eex
<h2>Conditions d'utilisation</h2>
<p>
    La réutilisation des informations disponibles sur transport.data.gouv.fr est soumise à la licence ODbL.
</p>
<p>
    Il est précisé que la clause de partage à l’identique figurant à l’article 4.4 concerne les informations de même nature, de même granularité, de même conditions temporelles et de même emprise géographique.
</p>

apps/transport/lib/transport_web/templates/page/espace_producteur.html.eex
<div class="producer-space">
  <div class="pt-48">
    <div class="container pb-24">
      <%= breadcrumbs [@conn, :espace_producteur] %>
    </div>
  </div>
  <section class="section producer-actions">
    <div class="container">
      <h2><%= dgettext("espace-producteurs", "What would you like to do?") %></h2>
      <div class="producer-actions-flex">
        <div class="panel">
          <div class="update-header pb-24">
            <img height=40 src="<%= static_path(@conn, "/images/producteurs/picto-maj.png") %>" alt="">
            <div>
              <h4 class="with-link"><%= dgettext("espace-producteurs", "Update a dataset") %></h4>
              <a href="https://doc.transport.data.gouv.fr/producteurs/mettre-a-jour-des-donnees"><%= dgettext("espace-producteurs", "updating a dataset guidelines") %></a>
            </div>
          </div>
          <div class="resource-list">
            <%= if @datasets == [] do %>
              <%= dgettext("espace-producteurs", "You have no resource to update for the moment") %>
            <% end %>
            <%= for dataset <- @datasets do %>
              <div class="pt-24 panel dataset-item">
                <strong><%= dataset.title %></strong>
                <div class="pt-12">
                  <%= link(dgettext("espace-producteurs", "Update a resource"),to: resource_path(@conn, :resources_list, dataset.datagouv_id), class: "button-outline primary small") %>
                  <%= link(dgettext("espace-producteurs", "Add a resource"),to: resource_path(@conn, :form, dataset.datagouv_id), class: "button-outline secondary small") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div>
          <div class="panel espace-producer-panel">
            <img height=40 src="<%= static_path(@conn, "/images/producteurs/picto-publier.png") %>" alt="">
            <div>
              <div class="publish-header">
                <div>
                  <h4 class="with-link"><%= dgettext("espace-producteurs", "Publish a dataset") %></h4>
                  <a href="https://doc.transport.data.gouv.fr/producteurs/comment-et-pourquoi-les-producteurs-de-donnees-utilisent-ils-le-pan"><%= dgettext("espace-producteurs", "Adding a dataset guidelines") %></a>
                </div>
              </div>
              <div class="pt-24">
                <%= dgettext("espace-producteurs", "Get your mobility data on the National Access Point. You will be redirected to data.gouv.fr to have your data published.") %>
              </div>
              <div class="pt-12">
                <a href="<%= dataset_creation() %>" class="button primary"><%= dgettext("espace-producteurs", "Publish a new dataset") %></a>
              </div>
            </div>
          </div>
          <div class="contact-us is-centered pt-24">
            <div>
              <img height=70 src="<%= static_path(@conn, "/images/producteurs/streamline-icon-headphones-customer-support-human@140x140.png") %>" alt="contact">
            </div>
            <h3><%= dgettext("espace-producteurs", "Contact us") %></h3>
            <div>
              <%= dgettext("espace-producteurs", "If you have any question on how to publish or update your data and you can't find an anwser on the website, do not hesitate, contact us:") %>
            </div>
            <div class="pt-12">
              <a href='mailto:<%= @contact_email %>'><%= @contact_email %></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div class="tramway">
    <img src="<%= static_path(@conn, "/images/producteurs/tramway.svg") %>" alt="">
  </div>
  <section class="section">
    <div class="container">
      <h2><%= dgettext("espace-producteurs", "Useful tools and content") %></h2>
      <div class="producer-tools-content">
        <div class="panel">
          <div class="checklist-header">
            <img height=60 src="<%= static_path(@conn, "/images/producteurs/streamline-icon-employee-checklist.png") %>" alt="">
            <div>
              <h4><%= dgettext("espace-producteurs", "Publishing best practices") %></h4>
            </div>
          </div>
        </div>
        <div class="panel espace-producer-panel">
          <img height=40 src="<%= static_path(@conn, "/images/producteurs/picto-check.png") %>" alt="">
          <div>
            <div class="test-header">
              <div>
                <h4><%= dgettext("espace-producteurs", "Validate your datasets") %></h4>
              </div>
            </div>
            <div>
              <%= dgettext("espace-producteurs", "You can test your data online and check its validity.") %>
            </div>
            <div class="pt-24">
              <a href="<%= validation_path(@conn, :index) %>" class="button-outline primary"><%= dgettext("espace-producteurs", "Test a file") %></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

apps/transport/lib/transport_web/templates/page/index.html.eex
<div class="hero home-hero">
  <div class="hero__container">
    <div class="home-top-content">
      <div class="home-title">
        <h1><%= dgettext("page-index", "title") %></h1>
        <h2><%= dgettext("page-index", "subtitle") %></h2>
      </div>
      <div class="home-search">
        <div class="searchBar">
          <%= form_for @conn, dataset_path(@conn, :index), [method: "get"], fn f -> %>
          <h4> <%= dgettext("page-index", "Search data for a region, a city, a network…") %> </h4>
          <div class="pt-12">
            <%= search_input f, :q, [id: "autoComplete", tabindex: 1, autocomplete: "off", placeholder: "ex : Nouvelle-Aquitaine", "aria-label": dgettext("page-index", "Find dataset")] %>
          </div>
          <div class="autoCompleteResultsField">
            <div id="autoCompleteResults">
            </div>
          </div>
        <% end %>
      </div>
      <div class="pt-48">
        <h4> <%= dgettext("page-index", "You can also") %> </h4>
        <div class="home-other-search-methods">
          <div class="search-method">
            <a href="<%= stats_path(@conn, :index)%>">
              <img src="<%= static_path(@conn, "/images/icons/map.png") %>" alt="Cartes">
              <%= dgettext("page-index", "Use the map") %>
            </a>
          </div>
          <div class="search-method">
            <a href="https://doc.transport.data.gouv.fr/reutilisateurs/apis/">
              <img src="<%= static_path(@conn, "/images/icons/api.png") %>" alt="API">
              <%= dgettext("page-index", "Use our APIs") %>
            </a>
          </div>
          <div class="search-method">
            <a href=<%= dataset_path @conn, :index, order_by: "most_recent" %>>
              <img src="<%= static_path(@conn, "/images/icons/recently-added-datasets.png") %>" alt="API">
              <%= dgettext("page-index", "See newly added datasets") %> </a>
      </div>
      </div></div>
      </div>
      </div>
    </div>
</div>
<div id="chevron-hint">
  <a href="#pan-offer-descriptions">
    <span class="fa-stack fa-2x">
      <i class="fas fa-circle fa-stack-2x"></i>
      <i class="fas fa-chevron-down fa-stack-1x fa-inverse"></i>
    </span>
  </a>
</div>

<section class="section section-grey">
<div class="container">

<div id="pan-offer-descriptions">
  <div class="pan-offer">
    <%= dgettext("page-index", "A freely accessible service")%>
  </div>
  <div class="pan-offer">
    <%= dgettext("page-index", "ALL French open mobility data at the same place")%>
    <div class="pan-offer-subtitle pt-12">
      <%= dgettext("page-index", "Selected formats")%>
    </div>
    <div class="pan-offer-subtitle">
      <%= dgettext("page-index", "Selected licences")%>
    </div>
  </div>
    <div class="pan-offer">
      <%= dgettext("page-index", "Online tools to ease data reuses")%>
    </div>
</div>

  <div class="existing pt-48" id="datasets">
  <h1><%= dgettext("page-index", "Available data by theme")%></h1>
    <div class="available-data grid">
      <a class="tile" href="<%= dataset_path(@conn, :index, type: "public-transit") %>">
        <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bus.svg") %>" alt="" />
            <div class="tile__text">
              <h4 class=""><%= dgettext("page-index", "Public transit schedules") %></h4>
              <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["public-transit"] || 0) %></div>
            </div>
          </a>
          <a class="tile" href="<%= dataset_path(@conn, :index, type: "public-transit", filter: "has_realtime") %>">
                      <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bus-stop.svg") %>" alt="" />
          <div class="tile__text">
            <h4 class=""><%= dgettext("page-index", "Realtime public transit") %></h4>
            <div><%= dngettext("page-index", "dataset", "datasets", @count_public_transport_has_realtime || 0) %></div>
          </div>
        </a>
        <!-- 14 is the region « national » We defined coaches as buses not bound to a region or AOM -->
        <a class="tile" href="<%= dataset_path(@conn, :by_region, 14, "modes[]": "bus") %>">
        <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bus.svg") %>" alt="" />
        <div class="tile__text">
          <h4 class=""><%= dgettext("page-index", "Long distance coach") %></h4>
          <div><%= dngettext("page-index", "dataset", "datasets", @count_coach || 0) %></div>
        </div>
      </a>
      <a class="tile" href="<%= dataset_path(@conn, :index, type: "bike-sharing") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bicycle.svg") %>" alt="" />
      <div class="tile__text">
        <h4 class=""><%= dgettext("page-index", "Bike sharing") %></h4>
        <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["bike-sharing"] || 0) %></div>
      </div>
    </a>
    <a class="tile" href="<%= dataset_path(@conn, :index, type: "carpooling-areas") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/car.svg") %>" alt="" />
    <div class="tile__text">
      <h4 class=""><%= dgettext("page-index", "Car-sharing areas") %></h4>
      <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["carpooling-areas"] || 0) %></div>
    </div>
  </a>
  <a class="tile" href="<%= dataset_path(@conn, :index, type: "charging-stations") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/charge-station.svg") %>" alt="" />
  <div class="tile__text">
    <h4 class=""><%= dgettext("page-index", "Charging & refuelling stations") %></h4>
    <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["charging-stations"] || 0) %></div>
  </div>
</a>
<a class="tile" href="<%= dataset_path(@conn, :index, type: "air-transport") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/plane.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Air data") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["air-transport"] || 0) %></div>
</div>
</a>
<a class="tile" href="<%= dataset_path(@conn, :index, "modes[]": "rail") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/train.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Railroad data") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_train || 0) %></div>
</div>
</a>
<a class="tile" href="<%= dataset_path(@conn, :index, type: "road-network") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/map.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Road networks") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["road-network"] || 0) %></div>
</div>
</a>
<a class="tile" href="<%= dataset_path(@conn, :index, "modes[]": "ferry") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/boat.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Sea and river transport") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_boat || 0) %></div>
</div>
</a>
<a class="tile" href="<%= dataset_path(@conn, :index, type: "addresses") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/addresses.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Addresses") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["addresses"] || 0) %></div>
</div>
</a>
<a class="tile" href="<%= dataset_path(@conn, :index, type: "informations") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/infos.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Other informations") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["informations"] || 0) %></div>
</div>
</a>
<a class="tile" href="<%= dataset_path(@conn, :index, type: "private-parking") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/parking.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Private parking") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["private-parking"] || 0) %></div>
</div>
<a class="tile" href="<%= dataset_path(@conn, :index, type: "bike-path") %>">
                          <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bike-path.svg") %>" alt="" />
<div class="tile__text">
  <h4 class=""><%= dgettext("page-index", "Bike path") %></h4>
  <div><%= dngettext("page-index", "dataset", "datasets", @count_by_type["bike-path"] || 0) %></div>
</div>
</a>
</div>
</div>
<div class="upcoming">
  <h2><%= dgettext("page-index", "Coming soon") %></h2>
  <div class="grid">
    <div class="tile">
      <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bicycle-parking.svg") %>" alt="" />
      <h3 class="text-center"><%= dgettext("page-index", "Bike parking") %></h3>
    </div>
    <div class="tile">
      <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/scooter-grey.svg") %>" alt="" />
      <h3 class="text-center"><%= dgettext("page-index", "Freefloating vehicles") %></h3>
    </div>
    <div class="tile">
      <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/construction-zone-grey.svg") %>" alt="" />
      <h3 class="text-center"><%= dgettext("page-index", "Road works") %></h3>
    </div>
  </div>
  <a href="#mailing-list"><%= dgettext("page-index", "I'd like to be informed") %></a>
</div>
</div>
</section>
<section class="section section" id="territory">
  <div class="container">
    <div class="row">
      <div class="section__description">
        <h2><%= dgettext("page-index", "Territory coverage") %></h2>
        <p><%= dgettext("page-index", "Scheduled public transit") %></p>
        <div class="row key-numbers">
          <div class="key-number__item">
            <strong><%= @count_aoms_with_dataset %></strong>
            <div>
              <%= dgettext("page-index", "Territories covered") |> raw() %>
              <br />
              <%= dgettext("page-index", "on") %> 330
            </div>
          </div>
          <div class="key-number__item">
            <strong><%= @count_regions_completed %></strong>
            <div>
              <%= dgettext("page-index", "Regions covered") %><br />
              <%= dgettext("page-index", "on") %> 18
            </div>
          </div>
          <div class="key-number__item">
            <strong><%= @percent_population %>%</strong>
            <div>
              <%= dgettext("page-index", "of the population") %>
              <br />
              <%= dgettext("page-index", "covered") %></div>
          </div>
        </div>
      </div>
      <div class="deployment-map">
        <a href="<%= static_path(@conn, "/stats") %>" class="text-center" role="link">
                    <img class="illustration" src="<%= static_path(@conn, "/images/france.svg") %>" alt="" />
        <div><%= dgettext("page-index", "See more statistics") %></div>
      </a>
    </div>
  </div>
</div>
</section>
<section class="section section-grey">
  <div class="container">
    <div class="row">
      <div class="section__description">
        <h2><%= dgettext("page-index", "Are you producing transport data ?") %></h2>
        <p><%= dgettext("page-index", "producer description") |> raw() %></p>
        <div class="row">
          <a class="button" href="<%= page_path(@conn, :infos_producteurs) %>" ><%= gettext("Producer informations") %></a>
        </div>
      </div>
      <img class="illustration" src="<%= static_path(@conn, "/images/bus.svg") %>" alt="" />
        </div>
      </div>
    </section>
    <section class="section reusers">
      <div class="container">
        <h2 class="text-center"><%= dgettext("page-index", "Who is reusing data from") %> transport.data.gouv.fr ?</h2>
        <div class="reusers__logos">
          <%= for reuser <- @reusers do %>
            <%= link(
                img_tag(static_path(@conn, "/images/logos/#{reuser["image"]}"), alt: reuser["name"]),
                to: reuser["website"]
            )
            %>
          <% end %>
        </div>
        <p class="text-center"><%= dgettext("page-index", "reusers list description") %> <a href=""><%= link(dgettext("page-index", "Learn more"), to: "https://doc.transport.data.gouv.fr/reutilisateurs/outils-pour-les-reutilisateurs") %></a>.</p>
      </div>
    </section>
    <section class="section section-grey mailing-list" id="mailing-list">
      <%= render "join_the_community.html", conn: @conn, mailchimp_newsletter_url: @mailchimp_newsletter_url %>
    </section>
    <script src="<%= static_path(@conn, "/js/autocomplete.js") %>"></script>